"""Make attempt submitted_at nullable

Revision ID: 254cef298bc8
Revises: 59d9f93d51c4
Create Date: 2026-08-08 16:52:52.916638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '254cef298bc8'
down_revision = '59d9f93d51c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
