"""add username and profile_photo to user

Revision ID: 849a02889062
Revises: d6a00da2b234
Create Date: 2026-08-16 13:42:44.271664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849a02889062'
down_revision = 'd6a00da2b234'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))

    users = connection.execute(sa.text("SELECT id, name, email FROM user WHERE username IS NULL OR username = ''")).fetchall()
    for user_id, name, email in users:
        base_username = (email.split('@')[0] if email else name).lower()
        base_username = ''.join(c for c in base_username if c.isalnum()) or f"user{user_id}"
        username = base_username
        counter = 1
        while connection.execute(sa.text("SELECT id FROM user WHERE username = :u AND id != :id"), {"u": username, "id": user_id}).fetchone():
            username = f"{base_username}{counter}"
            counter += 1
        connection.execute(sa.text("UPDATE user SET username = :u WHERE id = :id"), {"u": username, "id": user_id})

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', existing_type=sa.String(length=50), nullable=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
