"""Add started_at to attempts

Revision ID: d6a00da2b234
Revises: 254cef298bc8
Create Date: 2026-08-08 18:16:54.836492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a00da2b234'
down_revision = '254cef298bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
